services:
  database:
    image: mysql:9.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: app
      PMA_PASSWORD: app
    ports:
      - "8081:80"
    depends_on:
      - database

volumes:
  database_data:
